### ISSUE TITLE
Add `module-info.java`

### ISSUE THREAD

**Issue by overheadhunter** [patrickfav/hkdf#9]
Hi,

There hasn't been much activity in this repo for some time, so I hope you're still involved.

I'd like to request to make this a modular jar, as downstream projects would benefit from it.

Using multi-release jars, it is possible to do so while staying compatible with the pre-java 9 world (including Android). I've done this multiple times myself and would like to help out with a PR. However, I don't really know if you're using Maven or Gradle to build this lib, as the repo contains both.

Cheers!

**Comment by patrickfav** [comment]
A PR would be very much appreciated. The reason this repo doesnt see any relevant activity is that HKDF is a quite straight forward and simple algorithm and I feel it does everything it needs. That doesnt mean its obsolete, just that I dont think it needs more than what it is.

**Comment by overheadhunter** [comment]
Sure, so which build system is being used here?

**Comment by overheadhunter** [comment]
I encountered a little problem: You have multiple projects that use the package `at.favre.lib.crypto` (e.g. bcrypt, to name another). If downstream projects (transitively) rely on more than one such library, they will end up with what is called a split package, which is no longer allowed.

There is no workaround. You need to rename the package. Which is a breaking change, so this needs to be released as a major version, according to semver.

Two questions arise:
1. First and most importantly: Are you even willing to publish a breaking change?
2. Which module name should we use? Usually related to the Maven coordinates, i.e. `at.favre.lib.hkdf`
3. Which package name should we use? De-facto standard is to start with the module name to avoid split packages, i.e. `at.favre.lib.hkdf.*`

**Comment by patrickfav** [comment]
Released as https://github.com/patrickfav/hkdf/releases/tag/v2.0.0, sorry for the delay
